### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000001",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000002",
  "amount" : 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "460a804c5ab445258b5241863ae5bb13",
  "accountNumber" : "1000000001",
  "amount" : 100
}

### query transactino
GET http://localhost:8080/transaction/c326f27c42b9439da348d7057bfc128b